server:
  port: 8512
spring:
  application:
    name: spring-cloud-consul-producer
  cloud:
    consul:
      host: localhost   #consul注册中心的服务地址
      port: 8500        #consul注册中心的对外端口
      discovery:
        serviceName: service-producer	# 注册到consul的服务名称